### ISSUE TITLE
Read Wii configuration for rumble option

### ISSUE THREAD

**Issue by DraconicNEO** [WiiLink24/set-personal-data#4]
I don't know how possible this is but there should be a Feature where the SPD checks if Rumble is enabled or Disabled in the Wii settings in order to determine whether Rumble is on or not.

If that isn't possible there should at least be a way to turn off rumble.

**Comment by SketchMaster2001** [comment]
We do not use the rumble at all, so we decided to take it out completely. As of 1790312, this is true. Closing.

**Comment by DraconicNEO** [comment]
> 
> 
> We do not use the rumble at all, so we decided to take it out completely. As of [1790312](https://github.com/WiiLink24/set-personal-data/commit/1790312f2765252bd88e98f14f5e68b6d0619140), this is true. Closing.

That's good, Rumble was getting very annoying.
