### ISSUE TITLE
Why can't we change the user's physical address?

### ISSUE THREAD

**Issue by jeffyjeffy1023** [WiiLink24/set-personal-data#6]
No, not the email address. I mean the actual physical address/phone number (e.g. Apartment 0925, Wiitown, TX +1 234-567-8910)
Also, will the "channel" get a more smooth Wii Settings-like interface? I know we can't just mod the actual SPD, but I know it's likely possible to make the UI elements smoother. Also, (sorry for making ANOTHER also) the Shift key on the keyboard should be pressed when B on the Wii Remote is pressed, just like on the real Wii Keyboard.

**Comment by oscie57** [comment]
The main reason is because it isn't needed yet for normal users. When Demae is released, I am sure a special version with your own address will be released. For now, none of our publicly available services use it, so it is not public either.

**Comment by jeffyjeffy1023** [comment]
> The main reason is because it isn't needed yet for normal users. When Demae is released, I am sure a special version with your own address will be released. For now, none of our publicly available services use it, so it is not public either.

Okay, this makes sense, but there /technically/ is already a channel that uses the user's location. The Fujifilm Print Channel, since it can just autofill your address. Again, minor, and you can punch it in manually, but it's there!

**Comment by oscie57** [comment]
We don't use the address feature in that channel, as it'd be highly insecure for us to store addresses and bank details, plus we aren't sending out products for it, so why would it be needed?
